import type { BlockDef, FieldDef } from './types.js';

/** Wix-style blocks whose point is motion. Every one stands still for visitors who turn off animations. */

const button = (prefix = ''): FieldDef[] => [
  { key: prefix ? `${prefix}ButtonLabel` : 'buttonLabel', label: prefix ? 'Second button label' : 'Button label', type: 'text' },
  { key: prefix ? `${prefix}ButtonLink` : 'buttonLink', label: prefix ? 'Second button link' : 'Button link', type: 'url' },
];

/** Entrance animations any block can use, like Wix's "Animation" panel. */
export const entranceAnimations = [
  { value: '', label: 'None' },
  { value: 'fade', label: 'Fade in' },
  { value: 'rise', label: 'Float up' },
  { value: 'slide-start', label: 'Slide from the start side' },
  { value: 'slide-end', label: 'Slide from the end side' },
  { value: 'zoom', label: 'Zoom in' },
  { value: 'flip', label: 'Flip in' },
  { value: 'blur', label: 'Blur in' },
  { value: 'reveal', label: 'Reveal (wipe)' },
];

export const animatedDefinitions: BlockDef[] = [
  {
    type: 'aurora-hero',
    label: 'Aurora hero',
    icon: 'mdi-creation',
    category: 'animated',
    description:
      'Glowing colors drifting behind a headline whose words rise in one by one, with a word that keeps changing and a light that follows the mouse.',
    fields: [
      { key: 'eyebrow', label: 'Small line above', type: 'text' },
      { key: 'title', label: 'Headline', type: 'text' },
      { key: 'words', label: 'Changing words', type: 'text', help: 'Separated by commas; they take turns at the end of the headline.' },
      { key: 'text', label: 'Text', type: 'textarea' },
      ...button(),
      ...button('second'),
      { key: 'color', label: 'Third glow color', type: 'color', help: 'The other two are the theme’s main and second colors.' },
      {
        key: 'look',
        label: 'Look',
        type: 'select',
        options: [
          { value: 'dark', label: 'Dark' },
          { value: 'light', label: 'Light' },
        ],
      },
    ],
    defaults: {
      eyebrow: 'Design studio',
      title: 'We craft',
      words: 'websites, brands, experiences',
      text: 'A small team making things that look good, load fast and feel alive.',
      buttonLabel: 'Start a project',
      buttonLink: '#contact',
      secondButtonLabel: 'See our work',
      secondButtonLink: '#projects',
      color: '#7c5cff',
      look: 'dark',
    },
  },
  {
    type: 'scroll-text',
    label: 'Scroll-lit text',
    icon: 'mdi-text-shadow',
    category: 'animated',
    description: 'A big statement whose words light up one after another as the visitor scrolls.',
    fields: [
      { key: 'eyebrow', label: 'Small line above', type: 'text' },
      { key: 'text', label: 'Statement', type: 'textarea' },
    ],
    defaults: {
      eyebrow: 'Our approach',
      text: 'We believe a website should feel like walking into a well designed room: calm, clear, and full of small surprises that make you want to stay a little longer.',
    },
  },
  {
    type: 'counters',
    label: 'Counters',
    icon: 'mdi-counter',
    category: 'animated',
    description: 'Numbers that count up when they come into view.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      {
        key: 'items',
        label: 'Numbers',
        type: 'list',
        itemLabel: 'label',
        max: 6,
        fields: [
          { key: 'value', label: 'Number', type: 'number' },
          { key: 'prefix', label: 'Before the number', type: 'text', help: 'e.g. $' },
          { key: 'suffix', label: 'After the number', type: 'text', help: 'e.g. + or %' },
          { key: 'label', label: 'Label', type: 'text' },
        ],
      },
    ],
    defaults: {
      title: 'In numbers',
      items: [
        { value: 12, prefix: '', suffix: '+', label: 'Years of work' },
        { value: 340, prefix: '', suffix: '', label: 'Projects delivered' },
        { value: 98, prefix: '', suffix: '%', label: 'Happy clients' },
        { value: 24, prefix: '', suffix: '/7', label: 'Support' },
      ],
    },
  },
  {
    type: 'logo-strip',
    label: 'Logo strip',
    icon: 'mdi-dots-horizontal-circle-outline',
    category: 'animated',
    description: 'Client or partner logos gliding past endlessly, grey until hovered.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      {
        key: 'logos',
        label: 'Logos',
        type: 'list',
        itemLabel: 'name',
        max: 30,
        fields: [
          { key: 'image', label: 'Logo', type: 'image' },
          { key: 'name', label: 'Name', type: 'text', help: 'Shown when there is no logo, and read by screen readers.' },
          { key: 'link', label: 'Link', type: 'url' },
        ],
      },
      { key: 'seconds', label: 'Seconds per loop', type: 'number' },
      { key: 'twoRows', label: 'Second row moving the other way', type: 'boolean' },
      {
        key: 'look',
        label: 'Background',
        type: 'select',
        help: 'Choose dark for white logos.',
        options: [
          { value: 'light', label: 'Light' },
          { value: 'dark', label: 'Dark' },
        ],
      },
    ],
    defaults: {
      title: 'Trusted by',
      logos: ['Northwind', 'Lumen', 'Atlas', 'Kite', 'Orbit', 'Juniper', 'Vertex', 'Harbor'].map((name) => ({ image: '', name, link: '' })),
      seconds: 30,
      twoRows: false,
      look: 'light',
    },
  },
  {
    type: 'horizontal-scroll',
    label: 'Horizontal scroll',
    icon: 'mdi-gesture-swipe-horizontal',
    category: 'animated',
    description: 'The page pauses while cards slide sideways as the visitor scrolls down, with a progress bar.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'text', label: 'Text', type: 'textarea' },
      {
        key: 'cards',
        label: 'Cards',
        type: 'list',
        itemLabel: 'title',
        max: 12,
        fields: [
          { key: 'image', label: 'Photo', type: 'image' },
          { key: 'tag', label: 'Tag', type: 'text' },
          { key: 'title', label: 'Title', type: 'text' },
          { key: 'text', label: 'Text', type: 'textarea' },
          { key: 'link', label: 'Link', type: 'url' },
        ],
      },
    ],
    defaults: {
      title: 'Selected work',
      text: 'Keep scrolling: the projects slide past.',
      cards: [
        { image: '', tag: 'Brand', title: 'Northwind Coffee', text: 'Identity and packaging for a roastery.', link: '' },
        { image: '', tag: 'Website', title: 'Lumen Studio', text: 'A portfolio that loads in under a second.', link: '' },
        { image: '', tag: 'App', title: 'Kite', text: 'Booking for climbing gyms.', link: '' },
        { image: '', tag: 'Campaign', title: 'Orbit Bikes', text: 'Launch films and a pop-up store.', link: '' },
        { image: '', tag: 'Website', title: 'Harbor Hotel', text: 'Rooms, rates and stories by the sea.', link: '' },
      ],
    },
  },
  {
    type: 'tilt-cards',
    label: '3D tilt cards',
    icon: 'mdi-rotate-3d-variant',
    category: 'animated',
    description: 'Cards that tilt toward the mouse in 3D, with a moving shine.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      {
        key: 'items',
        label: 'Cards',
        type: 'list',
        itemLabel: 'title',
        max: 8,
        fields: [
          { key: 'image', label: 'Photo or icon', type: 'image' },
          { key: 'icon', label: 'Icon name (if no photo)', type: 'text', help: 'A Material Design Icons name, e.g. mdi-rocket-launch' },
          { key: 'title', label: 'Title', type: 'text' },
          { key: 'text', label: 'Text', type: 'textarea' },
          { key: 'link', label: 'Link', type: 'url' },
        ],
      },
    ],
    defaults: {
      title: 'What we do',
      items: [
        { image: '', icon: 'mdi-palette-outline', title: 'Design', text: 'Interfaces people enjoy using.', link: '' },
        { image: '', icon: 'mdi-code-tags', title: 'Development', text: 'Fast, accessible, easy to edit.', link: '' },
        { image: '', icon: 'mdi-rocket-launch-outline', title: 'Launch', text: 'Hosting, analytics and growth.', link: '' },
      ],
    },
  },
  {
    type: 'flip-cards',
    label: 'Flip cards',
    icon: 'mdi-card-multiple-outline',
    category: 'animated',
    description: 'Cards that turn over on hover (or tap) to show more on the back.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      {
        key: 'items',
        label: 'Cards',
        type: 'list',
        itemLabel: 'title',
        max: 8,
        fields: [
          { key: 'image', label: 'Front photo', type: 'image' },
          { key: 'title', label: 'Front title', type: 'text' },
          { key: 'back', label: 'Back text', type: 'textarea' },
          ...button(),
        ],
      },
    ],
    defaults: {
      title: 'Meet the team',
      items: [
        {
          image: '',
          title: 'Sara, design',
          back: 'Loves typography, plants and very small details.',
          buttonLabel: 'Say hi',
          buttonLink: '',
        },
        { image: '', title: 'Omid, code', back: 'Makes things fast. Has opinions about coffee.', buttonLabel: 'Say hi', buttonLink: '' },
        {
          image: '',
          title: 'Lena, projects',
          back: 'Keeps every launch on time and every client calm.',
          buttonLabel: 'Say hi',
          buttonLink: '',
        },
      ],
    },
  },
  {
    type: 'before-after',
    label: 'Before / after',
    icon: 'mdi-compare-horizontal',
    category: 'animated',
    description: 'Two photos on top of each other with a handle to drag between them.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'before', label: 'Before photo', type: 'image' },
      { key: 'after', label: 'After photo', type: 'image' },
      { key: 'beforeLabel', label: 'Before label', type: 'text' },
      { key: 'afterLabel', label: 'After label', type: 'text' },
    ],
    defaults: { title: 'The difference', before: '', after: '', beforeLabel: 'Before', afterLabel: 'After' },
  },
  {
    type: 'testimonials',
    label: 'Testimonials',
    icon: 'mdi-comment-quote-outline',
    category: 'animated',
    description: 'Quotes that take turns, with a progress line and the person’s photo.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      {
        key: 'items',
        label: 'Quotes',
        type: 'list',
        itemLabel: 'name',
        max: 12,
        fields: [
          { key: 'quote', label: 'Quote', type: 'textarea' },
          { key: 'name', label: 'Name', type: 'text' },
          { key: 'role', label: 'Role or company', type: 'text' },
          { key: 'photo', label: 'Photo', type: 'image' },
        ],
      },
      { key: 'seconds', label: 'Seconds per quote', type: 'number' },
    ],
    defaults: {
      title: 'Kind words',
      items: [
        {
          quote: 'They understood what we wanted before we could explain it. The new site doubled our bookings.',
          name: 'Maryam K.',
          role: 'Harbor Hotel',
          photo: '',
        },
        {
          quote: 'Fast, friendly and honest about what matters. We will work with them again.',
          name: 'Daniel R.',
          role: 'Kite',
          photo: '',
        },
        { quote: 'Our customers keep telling us how good the shop feels to use.', name: 'Nora S.', role: 'Northwind Coffee', photo: '' },
      ],
      seconds: 6,
    },
  },
  {
    type: 'timeline',
    label: 'Timeline',
    icon: 'mdi-timeline-text-outline',
    category: 'animated',
    description: 'Milestones along a line that draws itself as the visitor scrolls.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      {
        key: 'items',
        label: 'Milestones',
        type: 'list',
        itemLabel: 'title',
        max: 20,
        fields: [
          { key: 'date', label: 'Date', type: 'text' },
          { key: 'title', label: 'Title', type: 'text' },
          { key: 'text', label: 'Text', type: 'textarea' },
        ],
      },
    ],
    defaults: {
      title: 'Our story',
      items: [
        { date: '2012', title: 'Two people, one table', text: 'The studio starts in a spare room.' },
        { date: '2016', title: 'First big client', text: 'A hotel group trusts us with all their sites.' },
        { date: '2020', title: 'A team of twenty', text: 'New office, new crafts: video and motion.' },
        { date: 'Today', title: 'Still curious', text: 'Every project still starts with listening.' },
      ],
    },
  },
  {
    type: 'parallax',
    label: 'Parallax layers',
    icon: 'mdi-layers-triple-outline',
    category: 'animated',
    description:
      'Layers of pictures that move at different speeds as the visitor scrolls (and a little with the mouse), giving depth. Without photos it shows layered hills in your colors.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'text', label: 'Text', type: 'textarea' },
      ...button(),
      {
        key: 'layers',
        label: 'Layers (back to front)',
        type: 'list',
        itemLabel: 'speed',
        max: 5,
        fields: [
          { key: 'image', label: 'Picture', type: 'image', help: 'Front layers look best as cut-outs (PNG/WebP with transparency).' },
          {
            key: 'speed',
            label: 'Movement',
            type: 'select',
            options: [
              { value: 'still', label: 'Still' },
              { value: 'slow', label: 'Slow' },
              { value: 'medium', label: 'Medium' },
              { value: 'fast', label: 'Fast' },
              { value: 'reverse', label: 'Against the scroll' },
            ],
          },
          {
            key: 'fit',
            label: 'Fit',
            type: 'select',
            options: [
              { value: 'cover', label: 'Fill the area' },
              { value: 'bottom', label: 'Sit at the bottom' },
            ],
          },
        ],
      },
      { key: 'mouse', label: 'Layers follow the mouse a little', type: 'boolean' },
      {
        key: 'height',
        label: 'Height',
        type: 'select',
        options: [
          { value: 'full', label: 'Full screen' },
          { value: 'tall', label: 'Tall' },
        ],
      },
    ],
    defaults: {
      title: 'Go further',
      text: 'Every layer moves at its own pace.',
      buttonLabel: 'Explore',
      buttonLink: '#',
      layers: [
        { image: '', speed: 'slow', fit: 'cover' },
        { image: '', speed: 'medium', fit: 'bottom' },
        { image: '', speed: 'fast', fit: 'bottom' },
      ],
      mouse: true,
      height: 'full',
    },
  },
  {
    type: 'sticky-story',
    label: 'Sticky story',
    icon: 'mdi-book-open-page-variant-outline',
    category: 'animated',
    description: 'A picture stays in place while the text scrolls past beside it; the picture changes with each step.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      {
        key: 'imageSide',
        label: 'Picture side',
        type: 'select',
        options: [
          { value: 'start', label: 'Start' },
          { value: 'end', label: 'End' },
        ],
      },
      {
        key: 'steps',
        label: 'Steps',
        type: 'list',
        itemLabel: 'title',
        max: 10,
        fields: [
          { key: 'image', label: 'Picture', type: 'image' },
          { key: 'eyebrow', label: 'Small line', type: 'text' },
          { key: 'title', label: 'Title', type: 'text' },
          { key: 'text', label: 'Text', type: 'textarea' },
        ],
      },
    ],
    defaults: {
      title: 'How it works',
      imageSide: 'start',
      steps: [
        {
          image: '',
          eyebrow: 'Step 1',
          title: 'We listen',
          text: 'A first call to understand who you are, who you serve and what success looks like.',
        },
        { image: '', eyebrow: 'Step 2', title: 'We sketch', text: 'Ideas on paper, then in the browser, shared with you every week.' },
        { image: '', eyebrow: 'Step 3', title: 'We build', text: 'Fast pages, easy editing, and every detail checked on real phones.' },
        { image: '', eyebrow: 'Step 4', title: 'We launch', text: 'Go live, measure, and keep improving together.' },
      ],
    },
  },
  {
    type: 'zoom-reveal',
    label: 'Zoom-in picture',
    icon: 'mdi-arrow-expand-all',
    category: 'animated',
    description: 'A small rounded picture grows until it fills the whole screen as the visitor scrolls, then its title fades in on top.',
    fields: [
      { key: 'eyebrow', label: 'Small line above', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'text', label: 'Text', type: 'textarea' },
      ...button(),
      { key: 'image', label: 'Picture', type: 'image' },
      { key: 'intro', label: 'Text before the picture grows', type: 'text', help: 'Shown large above the small picture.' },
    ],
    defaults: {
      eyebrow: 'New collection',
      title: 'Step inside',
      text: 'Scroll, and the picture opens up around you.',
      buttonLabel: 'Take a look',
      buttonLink: '#',
      image: '',
      intro: 'A closer look',
    },
  },
  {
    type: 'stacking-cards',
    label: 'Stacking cards',
    icon: 'mdi-card-multiple',
    category: 'animated',
    description: 'Big cards that pile up on top of each other as the visitor scrolls; the ones underneath shrink and dim.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      {
        key: 'cards',
        label: 'Cards',
        type: 'list',
        itemLabel: 'title',
        max: 8,
        fields: [
          { key: 'image', label: 'Photo', type: 'image' },
          { key: 'eyebrow', label: 'Small line', type: 'text' },
          { key: 'title', label: 'Title', type: 'text' },
          { key: 'text', label: 'Text', type: 'textarea' },
          { key: 'color', label: 'Card color', type: 'color' },
          ...button(),
        ],
      },
    ],
    defaults: {
      title: 'What we offer',
      cards: [
        {
          image: '',
          eyebrow: '01',
          title: 'Strategy',
          text: 'We find out what makes you different, and how to say it.',
          color: '#0f172a',
          buttonLabel: '',
          buttonLink: '',
        },
        {
          image: '',
          eyebrow: '02',
          title: 'Design',
          text: 'A look that fits you, from logo to every page.',
          color: '#1e3a8a',
          buttonLabel: '',
          buttonLink: '',
        },
        {
          image: '',
          eyebrow: '03',
          title: 'Build',
          text: 'Fast pages you can edit yourself, on any screen.',
          color: '#4c1d95',
          buttonLabel: '',
          buttonLink: '',
        },
        {
          image: '',
          eyebrow: '04',
          title: 'Grow',
          text: 'We measure what works and keep improving it.',
          color: '#831843',
          buttonLabel: 'Start a project',
          buttonLink: '#contact',
        },
      ],
    },
  },
  {
    type: 'scroll-marquee',
    label: 'Scroll-moved words',
    icon: 'mdi-format-letter-spacing-variant',
    category: 'animated',
    description: 'Rows of huge words sliding in opposite directions, moved by the visitor’s scrolling rather than a clock.',
    fields: [
      {
        key: 'rows',
        label: 'Rows',
        type: 'list',
        itemLabel: 'text',
        max: 5,
        fields: [
          { key: 'text', label: 'Words', type: 'text', help: 'Repeated across the row.' },
          {
            key: 'style',
            label: 'Style',
            type: 'select',
            options: [
              { value: 'solid', label: 'Solid' },
              { value: 'outline', label: 'Outline' },
              { value: 'accent', label: 'Main color' },
            ],
          },
        ],
      },
      {
        key: 'speed',
        label: 'Speed',
        type: 'select',
        options: [
          { value: 'slow', label: 'Slow' },
          { value: 'medium', label: 'Medium' },
          { value: 'fast', label: 'Fast' },
        ],
      },
      {
        key: 'look',
        label: 'Look',
        type: 'select',
        options: [
          { value: 'light', label: 'Light' },
          { value: 'dark', label: 'Dark' },
        ],
      },
    ],
    defaults: {
      rows: [
        { text: 'Design · Build · Launch', style: 'solid' },
        { text: 'Brands that move', style: 'outline' },
        { text: 'Made with care', style: 'accent' },
      ],
      speed: 'medium',
      look: 'light',
    },
  },
  {
    type: 'split-reveal',
    label: 'Opening picture',
    icon: 'mdi-arrow-split-vertical',
    category: 'animated',
    description: 'A picture cut in two halves that slide apart like doors as the visitor scrolls, uncovering a message behind.',
    fields: [
      { key: 'image', label: 'Picture', type: 'image' },
      { key: 'coverTitle', label: 'Title on the picture', type: 'text' },
      { key: 'eyebrow', label: 'Small line above', type: 'text' },
      { key: 'title', label: 'Title behind', type: 'text' },
      { key: 'text', label: 'Text behind', type: 'textarea' },
      ...button(),
      {
        key: 'direction',
        label: 'Opens',
        type: 'select',
        options: [
          { value: 'sideways', label: 'Sideways' },
          { value: 'up-down', label: 'Up and down' },
        ],
      },
    ],
    defaults: {
      image: '',
      coverTitle: 'Open up',
      eyebrow: 'Behind the scenes',
      title: 'Good work starts with a good question',
      text: 'We ask a lot of them, so the answer ends up simple.',
      buttonLabel: 'Ask us one',
      buttonLink: '#contact',
      direction: 'sideways',
    },
  },
  {
    type: 'floating-gallery',
    label: 'Floating photos',
    icon: 'mdi-image-multiple-outline',
    category: 'animated',
    description: 'Photos scattered around a title, drifting up at different speeds as the visitor scrolls, as if at different depths.',
    fields: [
      { key: 'eyebrow', label: 'Small line above', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'text', label: 'Text', type: 'textarea' },
      ...button(),
      {
        key: 'photos',
        label: 'Photos',
        type: 'list',
        itemLabel: 'caption',
        max: 8,
        fields: [
          { key: 'image', label: 'Photo', type: 'image' },
          { key: 'caption', label: 'Caption', type: 'text', help: 'Read by screen readers; shown on hover.' },
        ],
      },
    ],
    defaults: {
      eyebrow: 'Gallery',
      title: 'Moments from the studio',
      text: 'Some of what happens between the first sketch and the launch.',
      buttonLabel: 'See all projects',
      buttonLink: '#',
      photos: ['Sketching', 'Workshop', 'Coffee break', 'Prototype', 'Launch day', 'The team'].map((caption) => ({ image: '', caption })),
    },
  },
  {
    type: 'text-scramble',
    label: 'Decoding text',
    icon: 'mdi-matrix',
    category: 'animated',
    description: 'Big lines that take turns, each one settling out of scrambled letters as if being decoded.',
    fields: [
      { key: 'eyebrow', label: 'Small line above', type: 'text' },
      { key: 'lines', label: 'Lines', type: 'textarea', help: 'One per line; they take turns.' },
      { key: 'text', label: 'Text', type: 'textarea' },
      ...button(),
      { key: 'seconds', label: 'Seconds per line', type: 'number' },
      {
        key: 'look',
        label: 'Look',
        type: 'select',
        options: [
          { value: 'dark', label: 'Dark' },
          { value: 'light', label: 'Light' },
        ],
      },
    ],
    defaults: {
      eyebrow: 'Hello',
      lines: 'We design.\nWe build.\nWe launch.',
      text: 'Everything a good website needs, under one roof.',
      buttonLabel: 'Start a project',
      buttonLink: '#contact',
      seconds: 3,
      look: 'dark',
    },
  },
  {
    type: 'image-trail',
    label: 'Photo trail',
    icon: 'mdi-cursor-default-click-outline',
    category: 'animated',
    description: 'Moving the mouse over a big title leaves a trail of photos that pop up and fade away. On phones the photos sit in a row.',
    fields: [
      { key: 'eyebrow', label: 'Small line above', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'text', label: 'Text', type: 'textarea' },
      { key: 'hint', label: 'Hint', type: 'text', help: 'A small note asking the visitor to move the mouse.' },
      {
        key: 'photos',
        label: 'Photos',
        type: 'list',
        itemLabel: 'caption',
        max: 12,
        fields: [
          { key: 'image', label: 'Photo', type: 'image' },
          { key: 'caption', label: 'Caption', type: 'text', help: 'Read by screen readers.' },
        ],
      },
    ],
    defaults: {
      eyebrow: 'Portfolio',
      title: 'Ten years of making',
      text: 'Brands, books, buildings and everything in between.',
      hint: 'Move your mouse',
      photos: ['Poster', 'Packaging', 'Interior', 'Book cover', 'Signage', 'Website'].map((caption) => ({ image: '', caption })),
    },
  },
  {
    type: 'hover-list',
    label: 'Hover-reveal list',
    icon: 'mdi-format-list-text',
    category: 'animated',
    description:
      'A list of big titles; pointing at one shows its photo, floating along with the mouse. On phones each row has a small photo.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      {
        key: 'items',
        label: 'Rows',
        type: 'list',
        itemLabel: 'title',
        max: 20,
        fields: [
          { key: 'image', label: 'Photo', type: 'image' },
          { key: 'title', label: 'Title', type: 'text' },
          { key: 'meta', label: 'Small text at the end', type: 'text', help: 'e.g. a year or a category' },
          { key: 'link', label: 'Link', type: 'url' },
        ],
      },
    ],
    defaults: {
      title: 'Recent projects',
      items: [
        { image: '', title: 'Northwind Coffee', meta: 'Brand · 2026', link: '' },
        { image: '', title: 'Lumen Studio', meta: 'Website · 2026', link: '' },
        { image: '', title: 'Harbor Hotel', meta: 'Website · 2025', link: '' },
        { image: '', title: 'Orbit Bikes', meta: 'Campaign · 2025', link: '' },
      ],
    },
  },
  {
    type: 'spinning-badge',
    label: 'Spinning badge',
    icon: 'mdi-rotate-orbit',
    category: 'animated',
    description: 'Words running around a circle that turns slowly, and faster while the visitor scrolls, beside a title.',
    fields: [
      { key: 'eyebrow', label: 'Small line above', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'text', label: 'Text', type: 'textarea' },
      ...button(),
      { key: 'badgeText', label: 'Words around the circle', type: 'text', help: 'Repeated to fill the circle.' },
      { key: 'image', label: 'Picture in the middle', type: 'image' },
      {
        key: 'icon',
        label: 'Icon in the middle (if no picture)',
        type: 'text',
        help: 'A Material Design Icons name, e.g. mdi-star-four-points',
      },
      {
        key: 'badgeSide',
        label: 'Badge side',
        type: 'select',
        options: [
          { value: 'end', label: 'End' },
          { value: 'start', label: 'Start' },
        ],
      },
    ],
    defaults: {
      eyebrow: 'Since 2012',
      title: 'Small studio, big ideas',
      text: 'We work with a handful of clients at a time, so every one gets our full attention.',
      buttonLabel: 'Meet us',
      buttonLink: '#about',
      badgeText: 'Design · Build · Launch ·',
      image: '',
      icon: 'mdi-star-four-points',
      badgeSide: 'end',
    },
  },
  {
    type: 'expanding-panels',
    label: 'Expanding panels',
    icon: 'mdi-view-column-outline',
    category: 'animated',
    description: 'Tall photo panels side by side; the one pointed at (or tapped) widens and shows its text.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      {
        key: 'panels',
        label: 'Panels',
        type: 'list',
        itemLabel: 'title',
        max: 7,
        fields: [
          { key: 'image', label: 'Photo', type: 'image' },
          { key: 'title', label: 'Title', type: 'text' },
          { key: 'text', label: 'Text', type: 'textarea' },
          { key: 'link', label: 'Link', type: 'url' },
        ],
      },
    ],
    defaults: {
      title: 'Explore the rooms',
      panels: [
        { image: '', title: 'Lobby', text: 'Light, plants and the best coffee in town.', link: '' },
        { image: '', title: 'Suites', text: 'Wide windows over the harbor.', link: '' },
        { image: '', title: 'Spa', text: 'A warm pool and quiet corners.', link: '' },
        { image: '', title: 'Rooftop', text: 'Sunsets, small plates, long evenings.', link: '' },
      ],
    },
  },
  {
    type: 'progress-bars',
    label: 'Skill bars',
    icon: 'mdi-chart-bar',
    category: 'animated',
    description: 'Bars that fill up, with their percentage counting along, when they come into view.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'text', label: 'Text', type: 'textarea' },
      {
        key: 'items',
        label: 'Bars',
        type: 'list',
        itemLabel: 'label',
        max: 12,
        fields: [
          { key: 'label', label: 'Label', type: 'text' },
          { key: 'value', label: 'Percent', type: 'number', help: 'From 0 to 100.' },
        ],
      },
    ],
    defaults: {
      title: 'What we are good at',
      text: 'Ten years of projects, measured honestly.',
      items: [
        { label: 'Brand identity', value: 95 },
        { label: 'Web design', value: 90 },
        { label: 'Development', value: 85 },
        { label: 'Motion', value: 70 },
      ],
    },
  },
  {
    type: 'picture-text',
    label: 'Picture in letters',
    icon: 'mdi-format-color-text',
    category: 'animated',
    description: 'Huge letters filled with a photo that glides and zooms inside them as the visitor scrolls.',
    fields: [
      { key: 'eyebrow', label: 'Small line above', type: 'text' },
      { key: 'word', label: 'Big word', type: 'text', help: 'Short words fill best.' },
      { key: 'image', label: 'Photo inside the letters', type: 'image' },
      { key: 'text', label: 'Text below', type: 'textarea' },
      {
        key: 'look',
        label: 'Look',
        type: 'select',
        options: [
          { value: 'light', label: 'Light' },
          { value: 'dark', label: 'Dark' },
        ],
      },
    ],
    defaults: {
      eyebrow: 'Made by the sea',
      word: 'OCEAN',
      image: '',
      text: 'Everything we make starts with a walk along the water.',
      look: 'light',
    },
  },
  {
    type: 'orbit',
    label: 'Orbiting icons',
    icon: 'mdi-orbit',
    category: 'animated',
    description: 'Logos or icons circling a title on two rings turning opposite ways; they stop while pointed at.',
    fields: [
      { key: 'eyebrow', label: 'Small line above', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'text', label: 'Text', type: 'textarea' },
      ...button(),
      {
        key: 'items',
        label: 'Icons',
        type: 'list',
        itemLabel: 'name',
        max: 14,
        fields: [
          { key: 'image', label: 'Logo', type: 'image' },
          { key: 'icon', label: 'Icon name (if no logo)', type: 'text', help: 'A Material Design Icons name, e.g. mdi-slack' },
          { key: 'name', label: 'Name', type: 'text', help: 'Read by screen readers and shown on hover.' },
        ],
      },
      { key: 'seconds', label: 'Seconds per turn', type: 'number' },
    ],
    defaults: {
      eyebrow: 'Works with',
      title: 'Everything you already use',
      text: 'Connect your favourite tools in a few clicks.',
      buttonLabel: 'See all integrations',
      buttonLink: '#',
      items: [
        ['mdi-google', 'Google'],
        ['mdi-slack', 'Slack'],
        ['mdi-github', 'GitHub'],
        ['mdi-dropbox', 'Dropbox'],
        ['mdi-wordpress', 'WordPress'],
        ['mdi-trello', 'Trello'],
        ['mdi-spotify', 'Spotify'],
        ['mdi-instagram', 'Instagram'],
        ['mdi-linkedin', 'LinkedIn'],
        ['mdi-youtube', 'YouTube'],
      ].map(([icon, name]) => ({ image: '', icon, name })),
      seconds: 40,
    },
  },
  {
    type: 'card-fan',
    label: 'Fanning cards',
    icon: 'mdi-cards-outline',
    category: 'animated',
    description: 'A pile of cards in the middle of the screen that spreads out into a fan as the visitor scrolls.',
    fields: [
      { key: 'eyebrow', label: 'Small line above', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'text', label: 'Text', type: 'textarea' },
      {
        key: 'cards',
        label: 'Cards',
        type: 'list',
        itemLabel: 'title',
        max: 7,
        fields: [
          { key: 'image', label: 'Photo', type: 'image' },
          { key: 'title', label: 'Title', type: 'text' },
          { key: 'text', label: 'Text', type: 'text' },
        ],
      },
    ],
    defaults: {
      eyebrow: 'The collection',
      title: 'Five ways to begin',
      text: 'Pick the one that fits; mix them as you go.',
      cards: [
        { image: '', title: 'Starter', text: 'One page, live this week.' },
        { image: '', title: 'Shop', text: 'Sell online from day one.' },
        { image: '', title: 'Studio', text: 'A portfolio that loads fast.' },
        { image: '', title: 'Hotel', text: 'Rooms, rates and bookings.' },
        { image: '', title: 'Custom', text: 'Built around you.' },
      ],
    },
  },
  {
    type: 'photo-columns',
    label: 'Endless photo columns',
    icon: 'mdi-view-parallel-outline',
    category: 'animated',
    description: 'A title beside columns of photos gliding up and down forever, each column the other way.',
    fields: [
      { key: 'eyebrow', label: 'Small line above', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'text', label: 'Text', type: 'textarea' },
      ...button(),
      {
        key: 'photos',
        label: 'Photos',
        type: 'list',
        itemLabel: 'caption',
        max: 18,
        fields: [
          { key: 'image', label: 'Photo', type: 'image' },
          { key: 'caption', label: 'Caption', type: 'text', help: 'Read by screen readers.' },
        ],
      },
      { key: 'seconds', label: 'Seconds per loop', type: 'number' },
      {
        key: 'look',
        label: 'Look',
        type: 'select',
        options: [
          { value: 'light', label: 'Light' },
          { value: 'dark', label: 'Dark' },
        ],
      },
    ],
    defaults: {
      eyebrow: 'Photography',
      title: 'Stories in pictures',
      text: 'Weddings, portraits and travel, shot on film and digital.',
      buttonLabel: 'Book a session',
      buttonLink: '#contact',
      photos: ['Portrait', 'Wedding', 'Mountains', 'Street', 'Family', 'Coast', 'Studio', 'City', 'Forest'].map((caption) => ({
        image: '',
        caption,
      })),
      seconds: 30,
      look: 'light',
    },
  },
];
