import type { BlockDef } from './types.js';

/** Everyday blocks: a pricing table, a map, and a spacer/divider between sections. */
export const extraDefinitions: BlockDef[] = [
  {
    type: 'pricing',
    label: 'Pricing table',
    icon: 'mdi-tag-multiple-outline',
    category: 'cards',
    description: 'Plans side by side with prices, features and a button. Optional monthly / yearly switch.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'subtitle', label: 'Subtitle', type: 'textarea' },
      { key: 'currency', label: 'Currency', type: 'text', help: 'e.g. $, €, or تومان (shown after the price in Persian).' },
      { key: 'monthlyLabel', label: 'Monthly switch label', type: 'text' },
      { key: 'yearlyLabel', label: 'Yearly switch label', type: 'text', help: 'The switch appears when a plan has a yearly price.' },
      {
        key: 'plans',
        label: 'Plans',
        type: 'list',
        itemLabel: 'name',
        max: 5,
        fields: [
          { key: 'name', label: 'Name', type: 'text' },
          { key: 'price', label: 'Price', type: 'text', help: 'Text, so “Free” or “On request” work too.' },
          { key: 'yearlyPrice', label: 'Yearly price', type: 'text' },
          { key: 'period', label: 'Per (e.g. /month)', type: 'text' },
          { key: 'description', label: 'Short description', type: 'text' },
          { key: 'features', label: 'Features', type: 'textarea', help: 'One per line. Start a line with - for a feature not included.' },
          { key: 'buttonLabel', label: 'Button label', type: 'text' },
          { key: 'buttonLink', label: 'Button link', type: 'url' },
          { key: 'highlighted', label: 'Highlight this plan', type: 'boolean' },
          { key: 'badge', label: 'Badge (e.g. Most popular)', type: 'text' },
        ],
      },
    ],
    defaults: {
      title: 'Simple pricing',
      subtitle: 'Pick a plan; change it any time.',
      currency: '$',
      monthlyLabel: 'Monthly',
      yearlyLabel: 'Yearly (2 months free)',
      plans: [
        {
          name: 'Starter',
          price: '9',
          yearlyPrice: '90',
          period: '/month',
          description: 'For a personal site.',
          features: 'One website\nFree SSL\nEmail support\n-Custom domain',
          buttonLabel: 'Choose Starter',
          buttonLink: '#contact',
          highlighted: false,
          badge: '',
        },
        {
          name: 'Business',
          price: '29',
          yearlyPrice: '290',
          period: '/month',
          description: 'For a growing team.',
          features: 'Five websites\nFree SSL\nCustom domain\nPriority support',
          buttonLabel: 'Choose Business',
          buttonLink: '#contact',
          highlighted: true,
          badge: 'Most popular',
        },
        {
          name: 'Agency',
          price: '79',
          yearlyPrice: '790',
          period: '/month',
          description: 'For many clients.',
          features: 'Unlimited websites\nFree SSL\nCustom domains\nA dedicated manager',
          buttonLabel: 'Talk to us',
          buttonLink: '#contact',
          highlighted: false,
          badge: '',
        },
      ],
    },
  },
  {
    type: 'map',
    label: 'Map',
    icon: 'mdi-map-marker-radius-outline',
    category: 'contact',
    description: 'An OpenStreetMap map with a pin, beside your address, phone and opening hours, with links to open it in map apps.',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      {
        key: 'lat',
        label: 'Latitude',
        type: 'number',
        help: 'Right-click the place in Google Maps or OpenStreetMap to copy its coordinates.',
      },
      { key: 'lng', label: 'Longitude', type: 'number' },
      {
        key: 'zoom',
        label: 'Zoom',
        type: 'select',
        options: [
          { value: '13', label: 'City' },
          { value: '15', label: 'Neighbourhood' },
          { value: '17', label: 'Street' },
        ],
      },
      { key: 'address', label: 'Address', type: 'textarea' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'hours', label: 'Opening hours', type: 'textarea' },
      {
        key: 'layout',
        label: 'Layout',
        type: 'select',
        options: [
          { value: 'card', label: 'Map with a card on it' },
          { value: 'side', label: 'Map beside the details' },
        ],
      },
    ],
    defaults: {
      title: 'Visit us',
      lat: 35.7219,
      lng: 51.3347,
      zoom: '15',
      address: 'Tehran, Iran',
      phone: '',
      hours: 'Saturday–Wednesday, 9:00–17:00',
      layout: 'card',
    },
  },
  {
    type: 'spacer',
    label: 'Spacer / divider',
    icon: 'mdi-arrow-split-horizontal',
    category: 'content',
    description: 'Space between sections, with an optional line, dots, wave or slant.',
    fields: [
      {
        key: 'size',
        label: 'Height',
        type: 'select',
        options: [
          { value: 'sm', label: 'Small' },
          { value: 'md', label: 'Medium' },
          { value: 'lg', label: 'Large' },
        ],
      },
      {
        key: 'shape',
        label: 'Shape',
        type: 'select',
        options: [
          { value: 'none', label: 'Empty space' },
          { value: 'line', label: 'Line' },
          { value: 'dots', label: 'Dots' },
          { value: 'wave', label: 'Wave' },
          { value: 'slant', label: 'Slant' },
          { value: 'curve', label: 'Curve' },
        ],
      },
      {
        key: 'color',
        label: 'Color',
        type: 'select',
        options: [
          { value: 'primary', label: 'Main color' },
          { value: 'secondary', label: 'Second color' },
          { value: 'dark', label: 'Dark' },
          { value: 'surface', label: 'Panels' },
        ],
      },
      { key: 'flip', label: 'Upside down', type: 'boolean' },
    ],
    defaults: { size: 'md', shape: 'wave', color: 'primary', flip: false },
  },
];
